# Generated by Django 2.0 on 2018-02-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
