# Generated by Django 2.0 on 2018-02-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbook', '0002_auto_20180201_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=80, unique=True),
        ),
    ]
